# -*- coding: utf-8 -*-
"""cv lab(3).ipy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d8j-6gN66SOKAV2knKM-nca5hDwdAu8Z
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np

def manual_average_filter(image, kernel_size):
    if kernel_size % 2 == 0:
        raise ValueError("Kernel size must be odd.")

    height, width = image.shape
    output_image = np.zeros_like(image, dtype=np.float32)
    pad = kernel_size // 2
    padded_image = np.pad(image, pad_width=pad, mode='edge')

    for i in range(height):
        for j in range(width):

            neighborhood = padded_image[i:i + kernel_size, j:j + kernel_size]

            output_image[i, j] = np.mean(neighborhood)

    return output_image.astype(image.dtype)

def show_comparision(original, blur3, blur5, blur7):
    plt.figure(figsize=(12, 10))
    plt.subplot(2, 2, 1)
    plt.imshow(original, cmap='gray')
    plt.title("Original Grayscale Image")
    plt.axis('off')

    plt.subplot(2, 2, 2)
    plt.imshow(blur3, cmap='gray')
    plt.title(f"Average Filter ({3},{3})")
    plt.axis('off')

    plt.subplot(2, 2, 3)
    plt.imshow(blur5, cmap='gray')
    plt.title(f"Average Filter ({5},{5})")
    plt.axis('off')

    plt.subplot(2, 2, 4)
    plt.imshow(blur7, cmap='gray')
    plt.title(f"Average Filter ({7},{7})")
    plt.axis('off')

    plt.tight_layout()
    plt.show()
img = cv2.imread('/content/org cv img.jpeg', 0)

if img is None:
    print("Error: Image not found. Please ensure 'org cv img.jpeg' is in the /content/ directory.")
else:
    blur_3x3_manual = manual_average_filter(img, 3)
    blur_5x5_manual = manual_average_filter(img, 5)
    blur_7x7_manual = manual_average_filter(img, 7)
    show_comparision(img, blur_3x3_manual, blur_5x5_manual, blur_7x7_manual)

