# -*- coding: utf-8 -*-
"""CV_lab8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rypj_oODoipQFsbmppkgBRysQQRxD90e
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt

def image_filtering(img,kernel,p,s):
  m,n=img.shape;x,y=kernel.shape
  if p!=0:
    padded_img=np.pad(img,p,'constant')
  else:
    padded_img=img
  m=int((padded_img.shape[0]-x+2*p)/s)+1
  n=int((padded_img.shape[1]-y+2*p)/s)+1
  filtered_img=np.zeros((m,n))
  for i in range(m):
    for j in range(n):
      filtered_img[i,j]=np.sum(kernel*padded_img[i*s:i*s+x, j*s:j*s+y])
  return filtered_img

img=cv2.imread("/content/cv lab 4 img.jpeg")
grayscale = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
k_s=9

kernel = np.ones( (k_s, k_s),dtype=np.float32) / (k_s * k_s)
filtered_image=image_filtering(grayscale,kernel,0,1)

m, n = filtered_image.shape

plt.figure(figsize=(15,15))
plt.subplot(2, 2, 1)
plt.imshow(grayscale, cmap="gray")
plt.title("Original")

plt.subplot(2, 2, 2)
plt.imshow(filtered_image, cmap="gray")
plt.title("Filtered")
plt.show()

print("original size",grayscale.shape)
print("filtered size",filtered_image.shape)