# -*- coding: utf-8 -*-
"""cv lab 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RkuWPyGTQqkO8nE6cxXWQEBiO4J4Td18
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt

img1 = cv2.imread("/content/cv lab 2 img.jpeg")

# Check if the image was loaded successfully
if img1 is None:
    print("Error: Could not load the image. Please check the file path.")
else:
    grayscale1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
    pixels = np.zeros(256)
    for i in range(grayscale1.shape[0]):
        for j in range(grayscale1.shape[1]):
            PI = grayscale1[i, j]
            pixels[PI] += 1
    running_sum = np.zeros(256)
    for i in range(256):
        running_sum[i] = np.sum(pixels[:i+1])
    running_sum = running_sum / np.max(running_sum)
    running_sum = (running_sum * 255).astype(np.uint8)

    equalized1 = np.zeros_like(grayscale1)

    for i in range(grayscale1.shape[0]):
        for j in range(grayscale1.shape[1]):
            equalized1[i, j] = running_sum[grayscale1[i, j]]
    plt.figure(figsize=(5, 4))

    plt.subplot(2, 2, 1)
    plt.imshow(grayscale1, cmap="gray")
    plt.title("Original Image", fontsize=14)
    plt.axis("off")

    plt.subplot(2, 2, 2)
    plt.hist(grayscale1.ravel(), 256, [0, 256], color="r")
    plt.title("Original Histogram", fontsize=14)
    plt.xlabel("Pixel Intensity")
    plt.ylabel("Pixel Count")

    plt.subplot(2, 2, 3)
    plt.imshow(equalized1, cmap="gray")
    plt.title("Equalized Image", fontsize=14)
    plt.axis("off")

    plt.subplot(2, 2, 4)
    plt.hist(equalized1.ravel(), 256, [0, 256], color="red")
    plt.title("Equalized Histogram", fontsize=14)
    plt.xlabel("Pixel Intensity")
    plt.ylabel("Pixel Count")
    plt.tight_layout()
    plt.savefig("Hist equalization1")
    plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt
pixels=np.arrange(range(256))
for i in range(Img.shape(0))
for j in range(Img shape(0))
PI = Img[i,j]
pixels[PI]+=1
running_sum=np.zeros(len(pixels))
fori in range(len(pixels))
running_sum[i]=np.sum(pixels[:i+1])
max_value=np.max(running_sum)
running_sum/=max_value
running_sum*=255
int(running_sum)
plt.savefig("Histogram Equalized Image.PNG")