# -*- coding: utf-8 -*-
"""cvlab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pNa187JeL0JTKojjZ0sbPwswjL4Q97ZJ
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt
def show_image(title, img, cmap=None):
  plt.figure(figsize=(5,5))
  plt.title(title)
  if cmap:
    plt.imshow(img, cmap=cmap)
  else:
    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
  plt.axis('off')
  plt.show()
img1 = cv2.imread('/content/Screenshot 2026-07-27 194900.png')
show_image("My Loaded Image", img1)
print(img1.shape)

resized_img = cv2.resize(img1, (300, 300))
show_image("Resized Image (300x300)", resized_img)

gray_img = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
show_image("Grayscale Image", gray_img, cmap='gray')

resized_img = cv2.resize(img2, (300, 300))
show_image("Resized Image (300x300)", resized_img)

gray_img = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
show_image("Grayscale Image", gray_img, cmap='gray')

img2 = cv2.imread('/content/Screenshot 2026-07-27 194912.png')
show_image("My Loaded Image", img2)
print(img2.shape)

img2 = cv2.resize(img2, (img1.shape[1], img1.shape[0]))
print(img1.shape)
print(img2.shape)

added_img = cv2.addWeighted(img1,0.5,img2,0.5,0)
show_image("Arithmetic Addition(blending)",added_img)

subtracted_img = cv2.subtract(img1,img2)
show_image("Arithmetic subtraction",subtracted_img)

rectangle = np.zeros((img1.shape[0],img1.shape[1]),dtype="uint8")
cv2.rectangle(rectangle,(50,50),(300,300),255,-1)

circle = np.zeros((img1.shape[0],img1.shape[1]),dtype="uint8")
cv2.circle(circle,(200,200),100,255,-1)

bitwise_and = cv2.bitwise_and(rectangle,circle)
show_image("BitwiseAND",bitwise_and,cmap='gray')

bitwise_or = cv2.bitwise_or(rectangle,circle)
show_image("BitwiseOR",bitwise_or,cmap='gray')

bitwise_xor = cv2.bitwise_xor(rectangle,circle)
show_image("BitwiseXOR",bitwise_xor,cmap='gray')

bitwise_not = cv2.bitwise_not(circle)
show_image("BitwiseNOT",bitwise_not,cmap='gray')

m, n, _ = img1.shape
rotated_img = np.zeros((n, m, 3), dtype=np.uint8)
for i in range(m):
    for j in range(n):
        rotated_img[j, m - 1 - i] = img1[i, j]
show_image("Rotated Image", rotated_img)

m, n, _ = img2.shape
rotated_img = np.zeros((n, m, 3), dtype=np.uint8)
for i in range(m):
    for j in range(n):
        rotated_img[j, m - 2 - i] = img2[i, j]
show_image("Rotated Image", rotated_img)