# -*- coding: utf-8 -*-
"""CV lab(6).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-_ang5Z9ta238aZcztHlRdaGjP5LVw51
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np

rmin=100
rmax=200
img=cv2.imread('/content/cv lab 6.jfif',0)
slicing_wo_background = np.zeros_like(img, dtype=np.uint8)
slicing_w_background = np.zeros_like(img, dtype=np.uint8)

for i in range(img.shape[0]):
  for j in range(img.shape[1]):
    pixel_value = img[i,j]
    if rmin <= pixel_value <= rmax:
      slicing_wo_background[i,j] = 255
    if rmin <= pixel_value <= rmax:
      slicing_w_background[i,j] = pixel_value

plt.figure(figsize=(15, 5))
plt.subplot(1, 3, 1), plt.imshow(img, cmap='gray'), plt.title('Original Image')
plt.subplot(1, 3, 2), plt.imshow(slicing_wo_background, cmap='gray'), plt.title('Slicing W/O Background (Slice White)')
plt.subplot(1, 3, 3), plt.imshow(slicing_w_background, cmap='gray'), plt.title('Slicing W Background (Slice Original)')
plt.show()